export enum PredefinedPermissions {
  // Company
  CREATE_COMPANY = 'CREATE_COMPANY',
  VIEW_COMPANY = 'VIEW_COMPANY',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  DELETE_COMPANY = 'DELETE_COMPANY',

  // Worker
  CREATE_WORKER = 'CREATE_WORKER',
  VIEW_WORKER = 'VIEW_WORKER',
  UPDATE_WORKER = 'UPDATE_WORKER',
  DELETE_WORKER = 'DELETE_WORKER',

  // Role type
  CREATE_ROLE_TYPE = 'CREATE_ROLE_TYPE',
  VIEW_ROLE_TYPE = 'VIEW_ROLE_TYPE',
  UPDATE_ROLE_TYPE = 'UPDATE_ROLE_TYPE',
  DELETE_ROLE_TYPE = 'DELETE_ROLE_TYPE',

  // Role assignment
  CREATE_ROLE_ASSIGNMENT = 'CREATE_ROLE_ASSIGNMENT',
  VIEW_ROLE_ASSIGNMENT = 'VIEW_ROLE_ASSIGNMENT',
  UPDATE_ROLE_ASSIGNMENT = 'UPDATE_ROLE_ASSIGNMENT',
  DELETE_ROLE_ASSIGNMENT = 'DELETE_ROLE_ASSIGNMENT',
}
